export const PRODUCTS_DATA = [
  {
    title: 'Lightning',
    order: 1,
    items: [
      {
        id: 1,
        name: 'Kaiser Idell 6740 Super',
        path: 'kaiser-idell-6740-super-lamp',
        price: 385,
        isSold: false,
        description:
          'Beautiful vintage black German design metal desk lamp by Kaiser Idell produced during 1930-1939 during the famous Bauhaus era. The metal “gooseneck“ allows various adjustments. The metal surface comes in enameled steel including a bakelite table clamp. German plug and E27 socket (bulb not included). Great working condition with beautiful patina.',
        images: {
          main: 'https://i.ibb.co/vD2t7Z5/main.png',
          thumbnail: 'https://i.ibb.co/8sdWnVK/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/Yys9LgT/sub-1.jpg',
            sub2: 'https://i.ibb.co/2F1m4zQ/sub-2.jpg',
            sub3: 'https://i.ibb.co/PMPTHXJ/sub-3.jpg',
            sub4: 'https://i.ibb.co/9bSjXfY/sub-4.jpg',
            sub5: 'https://i.ibb.co/GsNDD01/sub-5.jpg',
          },
        },
        specifications: {
          dimensions: 'L 70 x W 40 x H 20 cm',
          weight: '2,2 kg',
          number: 30170,
        },
      },
      {
        id: 2,
        name: 'Bauhaus table lamp',
        path: 'bauhaus-table-lamp',
        price: 140,
        isSold: false,
        description:
          'Beautiful vintage grey German design metal desk lamp inspired by the famous BAUHAUS era. The metal “gooseneck“ allows various adjustments. Original white cable, German plug and E27 socket (bulb not included). Excellent working condition.',
        images: {
          main: 'https://i.ibb.co/b7KG3DG/main.png',
          thumbnail: 'https://i.ibb.co/9bdc01z/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/fMzmW1t/sub-1.jpg',
            sub2: 'https://i.ibb.co/kMzywzd/sub-2.jpg',
            sub3: 'https://i.ibb.co/wSmxLh6/sub-3.jpg',
            sub4: 'https://i.ibb.co/Sm6cZ58/sub-4.jpg',
          },
        },
        specifications: {
          dimensions: 'L 23 x W 13,5 x H 47 cm',
          weight: '1,7 kg',
          number: 10024,
        },
      },
    ],
  },
  {
    title: 'Electronic',
    order: 2,
    items: [
      {
        id: 3,
        name: 'Braun KSM 11',
        path: 'braun-ksm-11-coffee-maker',
        price: 190,
        isSold: true,
        designer: ['reinhold-weiss'],
        description:
          'Braun KSM 11 coffee grinder designed by Reinhold Weiß in 1963, one of the most iconic design coffee grinders of all time. The grinder consists of a black plastic body and a polished chrome part. The KSM 11 works using spinning blades. The blades only get activated when the transparent plastic gets closed onto the body. Please note that there is a missing piece on the transparent cap from the bottom which however is not visible most of the time. Specifications: 40-60Hz 220V / 135 W',
        images: {
          main: 'https://i.ibb.co/ZVg2y2k/main.png',
          thumbnail: 'https://i.ibb.co/8XC44df/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/HXsnqDn/sub-1.jpg',
            sub2: 'https://i.ibb.co/T4PKDCy/sub-2.jpg',
            sub3: 'https://i.ibb.co/NxbNw86/sub-3.jpg',
            sub4: 'https://i.ibb.co/Gt6q5PY/sub-4.jpg',
            sub5: 'https://i.ibb.co/2WYV5Sv/sub-5.jpg',
          },
        },
        specifications: {
          dimensions: 'W 8 x L 8 x H 18 cm',
          weight: '1 kg',
          number: 30122,
        },
      },
      {
        id: 4,
        name: 'Braun KF 35',
        path: 'braun-kf-35-coffee-maker',
        price: 390,
        isSold: true,
        description: `This very rare Braun KF 35 is a successor of the Braun KF 20 and was designed by Hartwig Kahlcke in 1978. The yellow coffee maker is using one central heating. The name 'Traditional' (from Braun AG KF 35, Typ: 4053 Kaffeemaschine traditional) refers to the machine' s interrupted drip flow, which emulates a traditional pour over brew method. The coffee machine is in an excellent condition (almost as new) and fully operational. (220V / 40-60HZ, &50W - DE plug)`,
        images: {
          main: 'https://i.ibb.co/zSy0f4h/main.png',
          thumbnail: 'https://i.ibb.co/sqJjdNy/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/HBQPcfq/sub-1.jpg',
            sub2: 'https://i.ibb.co/V3YSw8V/sub-2.jpg',
            sub3: 'https://i.ibb.co/LRPhsfZ/sub-3.jpg',
            sub4: 'https://i.ibb.co/Qryv2hb/sub-4.jpg',
            sub5: 'https://i.ibb.co/hC1jtZH/sub-5.jpg',
            sub6: 'https://i.ibb.co/kyjQRFZ/sub-6.jpg',
          },
        },
        specifications: {
          dimensions: 'W 13 x L 29 x H 32 cm',
          weight: '1,8 kg',
          number: 30099,
        },
      },
      {
        id: 5,
        name: 'a8lla camcorder',
        path: 'a8lla-camcorder',
        price: 330,
        isSold: false,
        description: `Beautiful rare vintage "narrow" film camera from a8lla. The model h22k52 meopta is equipped with a well preserved and beautiful leather case. This beautiful piece of engineering design is in a very good condition and technically the camera seems to be in order(however we did not have a possibility to test it.and is in great condition, therefore it is being sold as a decoration piece to collectors.`,
        images: {
          main: 'https://i.ibb.co/jTXHJ33/main.png',
          thumbnail: 'https://i.ibb.co/xjD1HbC/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/3v2ck3T/sub-1.jpg',
            sub2: 'https://i.ibb.co/9yqFpTW/sub-2.jpg',
            sub3: 'https://i.ibb.co/kc6H8NW/sub-3.jpg',
            sub4: 'https://i.ibb.co/kgXMg4f/sub-4.jpg',
            sub5: 'https://i.ibb.co/xSgrHb2/sub-5.jpg',
            sub6: 'https://i.ibb.co/NmkPsV6/sub-6.jpg',
          },
        },
        specifications: {
          dimensions: 'W 16 x L 20 x H 5 cm',
          weight: '2 kg',
          number: 30104,
        },
      },
      {
        id: 6,
        name: 'Braun Nizo',
        path: 'braun-nizo-s-camcorder',
        price: 270,
        isSold: true,
        designer: ['dieter-rams'],
        description: `Braun Nizo S camera camcorder film - 8mm film camera designed 1970-77 by Dieter Rams. This beautiful piece of engineering design comes with additional equipment, such as an original BRAUN transportation leather bag, a shoulder stand and second lenses. Technically the camera seems to be in order and is in great condition, however it is sold as a decoration piece to Braun collectors. Please note that the images are reference images and each camera can vary slightly.`,
        images: {
          main: 'https://i.ibb.co/ww5SnWX/main.png',
          thumbnail: 'https://i.ibb.co/ZJThc60/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/HnL2hTs/sub-1.jpg',
            sub2: 'https://i.ibb.co/yBCwWDm/sub-2.jpg',
            sub3: 'https://i.ibb.co/HNpHkfV/sub-3.jpg',
            sub4: 'https://i.ibb.co/R32qVYr/sub-4.jpg',
          },
        },
        specifications: {
          dimensions: 'W 29 x L 11 x H 11 cm',
          weight: '2 kg',
          number: 30105,
        },
      },
      {
        id: 7,
        name: 'Siemens Schuckert fan',
        path: 'siemens-schuckert-fan',
        price: 260,
        isSold: false,
        description: `Beautiful original dark red metal Siemens & Schuckert fan, designed and manufactured in Germany in 1920s - 1930s during Bauhaus era. The metal housing is painted red and the iconic golden wire cage has the Siemens logo in the middle. The rotating is golden and made of metal. The industrial fan comes with white wire cable and German plug (220V). The fan might be operated through a switch on the bottom of the fan from Low, Medium to High Very good original condition with patina due to its age: partially reclaimed. Sold as decoration object. Working condition, but not intended for regular use due to 100 years of age.`,
        images: {
          main: 'https://i.ibb.co/qBpzkfR/main.png',
          thumbnail: 'https://i.ibb.co/1RCWX3v/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/TqVVDj8/sub-1.jpg',
            sub2: 'https://i.ibb.co/VVb31d0/sub-2.jpg',
            sub3: 'https://i.ibb.co/bbJX5d1/sub-3.jpg',
            sub4: 'https://i.ibb.co/zmRHWdv/sub-4.jpg',
          },
        },
        specifications: {
          dimensions: 'L 29 x W 15 x H 33 cm',
          weight: '2,4 kg',
          number: 30033,
        },
      },
      {
        id: 8,
        name: 'Braun ET 66',
        path: 'braun-et66-calculator',
        price: 125,
        isSold: false,
        designer: ['dieter-rams', 'dietrich-lubs'],
        description: `A new reissue of the original ET66 BRAUN calculator designed by Dieter Rams and Dietrich Lubs and introduced to market in 1987. The Braun ET66 calculator is considered to be the pinnacle of the “less but better” philosophy thanks to its simple, rectangular design with convex, circular buttons. A true product design icon, also exhibited in MOMA museum and inspiring Johny Ive from Apple.`,
        images: {
          main: 'https://i.ibb.co/wsWQfn1/main.png',
          thumbnail: 'https://i.ibb.co/rQVHnR6/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/n6JmJ8N/sub-1.jpg',
            sub2: 'https://i.ibb.co/JQyXxSx/sub-2.jpg',
            sub3: 'https://i.ibb.co/jRmj95T/sub-3.jpg',
          },
        },
        specifications: {
          dimensions: 'L 14 x W 8 x H 1 cm',
          weight: '0,4 kg',
          number: 30173,
        },
      },
      {
        id: 9,
        name: 'Braun HLD 4',
        path: 'braun-hld-4-hair-dryer',
        price: 130,
        isSold: true,
        designer: ['dieter-rams'],
        description: `Beautiful design classic hair dryer HLD 4 in red color. Designed by legendary Dieter Rams in 1970s. The foundation for the design was an new reconstructed version of the fan based on the HLD2 fan by Reinhold Weiss in 1963. The housing is made of orange/red plastic a minimal black switch on the front. The white cable wire is original and comes with an EU plug (220V). A must-have for every Braun collector. Excellent original condition with only very few almost invisible signs of use. Functionality: operational. Mainly intended for decoration purposes.`,
        images: {
          main: 'https://i.ibb.co/z8M1CHW/main.png',
          thumbnail: 'https://i.ibb.co/MMkHqvb/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/2nKb6XQ/sub-1.jpg',
            sub2: 'https://i.ibb.co/4dYBbZk/sub-2.jpg',
            sub3: 'https://i.ibb.co/HzpMTDr/sub-3.jpg',
            sub4: 'https://i.ibb.co/N7rgt0d/sub-4.jpg',
          },
        },
        specifications: {
          dimensions: 'L 14 x W 8 x H 5 cm',
          weight: '0,35 kg',
          number: 30017,
        },
      },
      {
        id: 10,
        name: 'Braun HLD-231',
        path: 'braun-hld-231-hair-dryer',
        price: 120,
        isSold: false,
        designer: ['reinhold-weiss'],
        description: `Beautiful design classic hair dryer HLD 4 in red color. Designed by legendary Dieter Rams in 1970s. The foundation for the design was an new reconstructed version of the fan based on the HLD2 fan by Reinhold Weiss in 1963. The housing is made of orange/red plastic a minimal black switch on the front. The white cable wire is original and comes with an EU plug (220V). A must-have for every Braun collector. Excellent original condition with only very few almost invisible signs of use. Functionality: operational. Mainly intended for decoration purposes.`,
        images: {
          main: 'https://i.ibb.co/wz4Yxvp/main.png',
          thumbnail: 'https://i.ibb.co/12ywF9j/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/7nvNbjs/sub-1.jpg',
            sub2: 'https://i.ibb.co/bzYbW4P/sub-2.jpg',
            sub3: 'https://i.ibb.co/vLbcGVT/sub-3.jpg',
            sub4: 'https://i.ibb.co/zSZYd8Y/sub-4.jpg',
            sub5: 'https://i.ibb.co/gjJvWc0/sub-5.jpg',
          },
        },
        specifications: {
          dimensions: 'L 14 x W 8 x H 5 cm',
          weight: '0,35 kg',
          number: 30095,
        },
      },
    ],
  },
  {
    title: 'Audio',
    order: 3,
    items: [
      {
        id: 11,
        name: 'Braun T 1000 CD',
        path: 'braun-t-1000-cd-radio',
        price: 1800,
        isSold: false,
        designer: ['dieter-rams'],
        description: `The Braun T 1000 CD marks the next generation of the 1964 T 1000 World Receiver and is one of the most iconic Braun radios designed under Dieter Rams. The main difference between the T 1000 and T 1000 CD is the leather strap handle and a round tuning knob. The T 1000 CD is one of the most sophisticated radios (even by today's standards) and is equipped with a complex range of functions. The switching between short, medium or long bands is achieved by rotating the drum on the side. The Braun T 1000 CD is fully functional & in great condition. The aluminum front is in great condition however it has been restored & painted over in silver color by the previous owner - one can hardly tell the difference to the original metal silver cover. Please note that the images are reference images and do not display the actual T 1000 CD however are very similar. The transistor radio comes does come without the power transformer and radio must be operated via batteries (not included). The operation manual is not included.
        
        Technical details: A universal receiver with 12 overlapping frequency bands used for AM (0.13 ... 30 MHz), 8 of which are shortwave. For 10 dB S / N, the sensitivity is better than 6uV. Battery-operated band selector with gold-plated contacts. 3 tuned RF circuits, 7 JFs. JF: 455 kHz, switchable + / 0.9 / + / 3.5 kHz bandwidth, manual gain control, BFO, AF filter, electronic band extension. FM range 87 ... 108 MHz, 1.4uV / 26 dB S / N limit level 2uV. The official retail price in 1964 has been: 1,400.00 DM`,
        images: {
          main: 'https://i.ibb.co/n1nb9C6/main.png',
          thumbnail: 'https://i.ibb.co/8gSdv5s/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/dm6T7kc/sub-1.jpg',
            sub2: 'https://i.ibb.co/BqL5GqH/sub-2.jpg',
            sub3: 'https://i.ibb.co/VBmwnSm/sub-3.jpg',
            sub4: 'https://i.ibb.co/G5tpQgp/sub-4.jpg',
            sub5: 'https://i.ibb.co/99XvCbq/sub-5.jpg',
            sub6: 'https://i.ibb.co/ThHjMBS/sub-6.jpg',
            sub7: 'https://i.ibb.co/BLJvjr5/sub-7.jpg',
          },
        },
        specifications: {
          dimensions: 'W 36 x L 26 x H 13,5cm',
          weight: '7,5 kg',
          number: 30141,
        },
      },
      {
        id: 12,
        name: 'Braun RT 20',
        path: 'braun-rt-20',
        price: 1980,
        isSold: false,
        description: `Beautiful iconic design classic radio by BRAUN RT 20. The RT20 has been designed in Germany by Dieter Rams between 1960-69. The buttons are arranged horizontally or vertically depending on their function. Originally designed for long, medium and FM radio, a phono (record player) could also be connected. The beveled front gives the unit additional dynamics, the lettering is silkscreened and usually defective, but on our example in excellent condition. The iconic speaker grille is substituted for the phono unit. Original rare manual and warranty card included! Exclusively available in our Only / Once shop.`,
        images: {
          main: 'https://i.ibb.co/27x785K/main.png',
          thumbnail: 'https://i.ibb.co/bgNB3YT/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/hy5vpVc/sub-1.jpg',
            sub2: 'https://i.ibb.co/RyHLFnF/sub-2.jpg',
            sub3: 'https://i.ibb.co/Km8WHPk/sub-3.jpg',
            sub4: 'https://i.ibb.co/kJw0wCw/sub-4.jpg',
            sub5: 'https://i.ibb.co/0GkTQ8y/sub-5.jpg',
            sub6: 'https://i.ibb.co/4mJChF7/sub-6.jpg',
            sub7: 'https://i.ibb.co/BPLNrB5/sub-7.jpg',
            sub8: 'https://i.ibb.co/3WNzqsy/sub-8.jpg',
            sub9: 'https://i.ibb.co/RphMbF0/sub-9.jpg',
          },
        },
        specifications: {
          dimensions: 'L 50 x W 26 x H 19 cm',
          weight: '8 kg',
          number: 30078,
        },
      },
      {
        id: 13,
        name: 'Braun Transistor K',
        path: 'braun-transistor-k',
        price: 580,
        isSold: false,
        designer: ['dieter-rams'],
        description: `Beautiful and rare design classic radio Kofferempfänger Transistor K from Braun. Designed in Germany by Dieter Rams in 1959–1961. The radio is made of grey plastic and is held by a brown leather belt. Technical specification: Superhet general; IF/IF 455 kHz; 3 AF stage(s) 6 circuit(s) AM / Wavebands: Long wave, medium wave and short wave. Operating mode: 6V battery (not included) Condition: Beautiful original condition. All functions working, radio is operating. Sold as decoration design object for BRAUN collectors - not intended for daily usage.`,
        images: {
          thumbnail: 'https://i.ibb.co/j8w3v5g/thumbnail.jpg ',
          main: 'https://i.ibb.co/6DDMyYP/main.png ',
          sub: {
            sub1: 'https://i.ibb.co/Vg7BDWP/sub-1.jpg ',
            sub2: 'https://i.ibb.co/x6CsV6G/sub-2.jpg ',
            sub3: 'https://i.ibb.co/P6hj3Rs/sub-3.jpg ',
            sub4: 'https://i.ibb.co/4Sj4wvC/sub-4.jpg ',
            sub5: 'https://i.ibb.co/0jTy4jV/sub-5.jpg ',
            sub6: 'https://i.ibb.co/dJG9ZhX/sub-6.jpg ',
            sub7: 'https://i.ibb.co/3RNhJjH/sub-7.jpg ',
            sub8: 'https://i.ibb.co/jr3CpSD/sub-8.jpg ',
            sub9: 'https://i.ibb.co/XDdddnG/sub-9.jpg ',
            sub10: 'https://i.ibb.co/25tP8s2/sub-10.jpg',
          },
        },
        specifications: {
          dimensions: ' L 20,5 x W 9,5 x H 22,5 cm',
          weight: '3,1 kg',
          number: 30112,
        },
      },
      {
        id: 14,
        name: 'Braun SK 2 / 2',
        path: 'braun-sk-2-2-radio-tuner',
        price: 470,
        isSold: true,
        description: `Beautiful and very rare design classic radio SK 2 / 2 by Braun. Designed in Germany by Artur Braun together with Dr. Fritz Eichler in 1955. The iconic & timeless radio is made of bakelite. The radio has been fully restored from inside and outside (new light grey paint). The SK 2 is fully functional and has been reclaimed by our Braun technician. The radio comes with an original 220V German cable. To be used for decoration purposes mainly, great for any Braun collector.`,
        images: {
          main: 'https://i.ibb.co/D7VVmWT/main.png',
          thumbnail: 'https://i.ibb.co/8XZ2q9n/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/zh6KHBr/sub-1.jpg',
            sub2: 'https://i.ibb.co/qmsnFjT/sub-2.jpg',
            sub3: 'https://i.ibb.co/WVTnsJ5/sub-3.jpg',
            sub4: 'https://i.ibb.co/PCWw5Yq/sub-4.jpg',
            sub5: 'https://i.ibb.co/tmrC04F/sub-5.jpg',
            sub6: 'https://i.ibb.co/WGN736m/sub-6.jpg',
          },
        },
        specifications: {
          dimensions: 'L 24 x W 13 x H 16 cm',
          weight: '3,5 kg',
          number: 30154,
        },
      },
      {
        id: 15,
        name: 'Braun CSV 13',
        path: 'braun-hi-fi-csv-13',
        price: 1850,
        isSold: false,
        designer: ['dieter-rams'],
        description: `The iconic Braun CSV 13 amplifier has been design by legendary designer Dieter Rams in the years 1961 in Germany. It marks Braun's first HiFi quality amplifier! This particular example is in great outer condition with very minor signs of use and has been revised and tested. Fully functional and operational.

Braun described its devices in the brochures as follows: The CSV 13 allows an unusually sensitive adjustment, music lovers know them therefore particularly appreciate. It satisfies them to be able to get the last bit of perfection out of a performance and to produce a balanced sound image under all circumstances. Monophonic or stereophonic turntables, tape recorders, radio receivers (tuners) and microphones can be connected to the inputs of the control amplifier. The tape connection is also an output for "recording" when one of the other inputs is being recorded. A rotary switch selects the desired operating mode, for record playback at the same time unfiltered (broadband) playback or - for suppression of noise with old and played records - the addition of treble filters of different "strength". Technical features: Output 2 x 12 watts / Tube amplifier system.`,
        images: {
          main: 'https://i.ibb.co/C62jZW3/main.png',
          thumbnail: 'https://i.ibb.co/j4T7t16/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/pXG0Fqz/sub-1.jpg',
            sub2: 'https://i.ibb.co/gF0F0rr/sub-2.jpg',
            sub3: 'https://i.ibb.co/hKxBHnq/sub-3.jpg',
            sub4: 'https://i.ibb.co/7YKqkX0/sub-4.jpg',
            sub5: 'https://i.ibb.co/mSbQvsD/sub-5.jpg',
            sub6: 'https://i.ibb.co/51vygF4/sub-6.jpg',
            sub7: 'https://i.ibb.co/D11kkMj/sub-7.jpg',
            sub8: 'https://i.ibb.co/HxZgB9m/sub-8.jpg',
            sub9: 'https://i.ibb.co/k2rKmHh/sub-9.jpg',
          },
        },
        specifications: {
          dimensions: 'L 34 x W 40 x H 12 cm',
          weight: '12 kg',
          number: 30150,
        },
      },
      {
        id: 16,
        name: 'Braun Hi-Fi CE 500 & CSV 250',
        path: 'braun-hi-fi-ce-500-csv-250',
        price: 2280,
        isSold: false,
        designer: ['dieter-rams'],
        description: `Braun Hi-Fi set consisting of Braun CSV 250/1 amplifier and CE 500 radio tuner designed by Dieter Rams. Great working condition: Both units are perfectly working and have been restored by our Braun technician (transistor changes) and come in a great outer condition - see images. The (link: https://onlyonce.com/product/acron-300-c-hi-fi-speakers text: Acron speakers) are available separately and not part of the set. Both, Amplifier & Radio units are also available separately - please contact us in this case.
**Technical specifications:** CE 500: Fully transistorized, high-quality tuner for radio reception on the wavebands VHF (stereo), medium and long wave. Version CE 501 K replaces long wave with short wave. Transmitter selection by separate transmitter selection knobs for AM and VHF. VHF module equipped with field effect transistor. Automatic VHF sharp tuning. Stereo display and large tuning meter. Accordance of maximum pointer deflection with ratio zero crossing. Ferrite antenna for MW and LW (KW). THD 0.5% at 1000 Hz with 40 kHz deviation, sensitivity 1 uV for 30 dB signal-to-noise ratio, limiting insert at 1.2 iiV, limiting effective in 5 steps. Selectivity 54 dB for 400 kHz according to IHF, crosstalk attenuation 35 dB at 1000 Hz with 40 kHz deviation.
CSV 250/1: Fully transistorized HiFi stereo amplifier with 2X65 watts of power (2x40 watts sine wave). Toggle switches for band control, rumble filter, noise filter, linear volume control, presence attenuated, mono and stereo operation, side swapping. Separate balance, bass and treble dividers. Mode switching by push buttons. Frequency response 10 ... 35 000 Hz, distortion factor <0.4%, crosstalk attenuation >47dB, impedance > 70 dB. Ironless power amplifiers with electronic fuse. Connections: Radio, phono, tape, microphone, reserve, speaker, headphones. Housing: sheet steel with anthracite gray ruffle varnish. Front panel made of aluminum.`,
        images: {
          main: 'https://i.ibb.co/SfNqh3V/main.png',
          thumbnail: 'https://i.ibb.co/BZHsnv8/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/1GY612W/sub-1.jpg',
            sub2: 'https://i.ibb.co/sQw9hkm/sub-2.jpg',
            sub3: 'https://i.ibb.co/6NzLtzv/sub-3.jpg',
            sub4: 'https://i.ibb.co/F6pT5Hh/sub-4.jpg',
            sub5: 'https://i.ibb.co/Hq7FFVB/sub-5.jpg',
            sub6: 'https://i.ibb.co/SXL2J15/sub-6.jpg',
          },
        },
        specifications: {
          dimensions: 'L 26 x W 32 x H 11 cm',
          weight: '10 kg',
          number: 30142,
        },
      },
      {
        id: 17,
        name: 'Braun CE 16',
        path: 'braun-hi-fi-ce-16-tuner',
        price: 990,
        isSold: false,
        designer: ['dieter-rams'],
        description: `The iconic Braun CE 16 Radio Tuner has been design by legendary designer Dieter Rams in the years 1967 - 1969 in Germany. This particular example is in great outer condition with very minor signs of use and has been revised and tested. Fully functional and operational.
Technical features: Reception ranges VHF 87-108 MHz / FM stereo / AM - medium wave 512-1640 kHz / Sensitivity 0.9 µV 30 dB signal-to-noise ratio / 40 kHz stroke / Selectivity 60 dB / 300 kHz / Distortion> 1% / Channel separation> 32 dB / AF output voltage FM 0.5 V / 40 kHz stroke; AM 0.5 V / 30% modulation (Ri = 10 kOhm) / Signal to noise ratio mono 60 dB / stereo 59 dB / Number of channels FM 14 / AM 11 / Fitted with 17 transistors, 14 germanium diodes, 4 silicon diodes / 220V & 110V / Special features: Automatic sharp tuning with VHF, HF display, tuning display by moving coil instrument, built-in stereo decoder, flywheel drive, gray sheet steel housing.`,
        images: {
          main: 'https://i.ibb.co/WVdyJ3k/main.png',
          thumbnail: 'https://i.ibb.co/DV8Pq9d/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/b3Mgx7K/sub-1.jpg',
            sub2: 'https://i.ibb.co/Lt8C52Z/sub-2.jpg',
            sub3: 'https://i.ibb.co/BZ9zfBY/sub-3.jpg',
            sub4: 'https://i.ibb.co/QYnN6jL/sub-4.jpg',
            sub5: 'https://i.ibb.co/MhJ547h/sub-5.jpg',
            sub6: 'https://i.ibb.co/3NJ269y/sub-6.jpg',
          },
        },
        specifications: {
          dimensions: ' L 34 x W 20 x H 11 cm',
          weight: '4,5 kg',
          number: 30135,
        },
      },
      {
        id: 18,
        name: 'Braun KH 1000',
        path: 'braun-kh-1000',
        price: 440,
        isSold: true,
        designer: ['reinhold-weiss'],
        description: `BRAUN KH 1000 headphones in its original packaging. Designed by Reinhold Weiß in 1967. Hi-Fi stereo headphones in studio quality. Listen to music with unrestricted dynamics and a full frequency range from 16 ... 20000Hz / 400 Ohm. Comfortable bracket and a large ear pads. Cable with DIN plug (adapter to modern cinch can be installed easily).`,
        images: {
          main: 'https://i.ibb.co/dDmVHNx/main.png',
          thumbnail: 'https://i.ibb.co/HBVwK9K/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/sFmTbp0/sub-1.jpg',
            sub2: 'https://i.ibb.co/xLNX6fg/sub-2.jpg',
            sub3: 'https://i.ibb.co/0ycv1Dz/sub-3.jpg',
            sub4: 'https://i.ibb.co/rwkwp9L/sub-4.jpg',
            sub5: 'https://i.ibb.co/N7yDHNb/sub-5.jpg',
            sub6: 'https://i.ibb.co/4jYQ5gV/sub-6.jpg',
            sub7: 'https://i.ibb.co/LSzt8jF/sub-7.jpg',
            sub8: 'https://i.ibb.co/brngcdg/sub-8.jpg',
          },
        },
        specifications: {
          dimensions: 'W 25 x L 30 x H 10 cm',
          weight: '0,8 kg',
          number: 33340,
        },
      },
      {
        id: 19,
        name: 'Braun TS 31',
        path: 'braun-ts-31-radio',
        price: 1150,
        isSold: false,
        description: `Original BRAUN TS 31 designed by Herbert Hirche in 1957 in Stuttgart, Germany. The TS 31 radio receiver appeared in the Braun catalogue in 1961 with a new RC82 chassis and is based on the the previous model (TS 3). The FM radio tuner is very powerful in terms of sensitivity & selectivity and delivers an outstanding stereo sound performance. This model is equipped with the "magical eye" (Magische Auge) which lights up in green light on the front operation module. The Braun TS31 is in excellent condition, especially the teak wood which looks almost as new (almost no coloring or scratches) since the previous owner has taken great care. The controls are fully functional and the radio is operating on 220V (contains 110V switch). Please note the given its age you will still hear a slight rustling sound, which only makes this piece of design history more authentic. All parts are original, even the vintage fiber on the front with great patina, the only exception is one of the connecting speaker wires on the back. Please note that we are selling the Braun TS 31 as a design collectors item, and although it is fully functional it is mainly intended for decoration purposes and not everyday use.`,
        images: {
          main: 'https://i.ibb.co/DC98zG9/main.png',
          thumbnail: 'https://i.ibb.co/s5ggPjH/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/6R9xZtF/sub-1.jpg',
            sub2: 'https://i.ibb.co/QFr47mr/sub-2.jpg',
            sub3: 'https://i.ibb.co/YBNSfjk/sub-3.jpg',
            sub4: 'https://i.ibb.co/vHsswr5/sub-4.jpg',
            sub5: 'https://i.ibb.co/kHhJCHr/sub-5.jpg',
            sub6: 'https://i.ibb.co/wWBLZ6h/sub-6.jpg',
            sub7: 'https://i.ibb.co/pZzQvZ8/sub-7.jpg',
          },
        },
        specifications: {
          dimensions: 'W 59 x L 33 x H 29 cm',
          weight: '15 kg',
          number: 30164,
        },
      },
      {
        id: 20,
        name: 'Braun ABR 314 df',
        path: 'braun-abr-314-ft',
        price: 180,
        isSold: false,
        designer: ['dietrich-lubs'],
        description: `Classic travel radio by Braun Type ABR 314 DF - typ 3869. Designed by Dietrich Lubs in 1980s – Germany. Use this beautiful design classic as an alarm or radio clock or simply just as a radio. This radio combines multiple top functions: digital search for radio stations, automatic adjustment of time & date, analog & digital clock, snooze for up to 60 minutes, display light & many more. The clock runs with a quite and precise Quartz mechanism. The front cover plastic can be opened and shows the world time zones on its back. The radio runs with 4 x AA batteries (not included). Excellent original condition with almost no signs of usage. Radio works seamlessly.`,
        images: {
          main: 'https://i.ibb.co/PzvwTj8/main.png',
          thumbnail: 'https://i.ibb.co/4JtyG1b/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/3vMJyTt/sub-1.jpg',
            sub2: 'https://i.ibb.co/02xCLJT/sub-2.jpg',
            sub3: 'https://i.ibb.co/PG1sBX4/sub-3.jpg',
            sub4: 'https://i.ibb.co/HBfmXGy/sub-4.jpg',
          },
        },
        specifications: {
          dimensions: 'W 16 x L 8 x H 3 cm',
          weight: '0,15 kg',
          number: 30180,
        },
      },
      {
        id: 21,
        name: 'Braun SK 5',
        path: 'braun-sk-5-2',
        price: 2200,
        isSold: true,
        designer: ['dieter-rams'],
        description: `The legendary Braun SK 5 has been designed by Hans Gugelot + Dieter Rams, in 1958. It is equipped with a vinyl player, radio unit and a built-in Braun speaker box. The SK5 is an absolute beauty and design classic that you will find in MOMA and other museums. The radio part has been extended for longwave reception (LW). The PC3 SV turntable has been equipped with a stereo crystal pickup system and thus prepared for stereo playback (SV ). The SK 5 remains a mono system. Condition: Well preserved original condition with slight patina (see images). It has been reclaimed with great effort and care while making sure to preserve all original parts. Both the speaker and transistor, as well as vinyl player are functional. All parts are original! Sold as a prestige design collectible, not intended for daily use!`,
        images: {
          main: 'https://i.ibb.co/GHFKrbJ/main.png',
          thumbnail: 'https://i.ibb.co/VC8xfmW/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/gzjry2Y/sub-1.jpg',
            sub2: 'https://i.ibb.co/b7n6SmW/sub-2.jpg',
            sub3: 'https://i.ibb.co/dGs4ZXR/sub-3.jpg',
            sub4: 'https://i.ibb.co/YRj5X5G/sub-4.jpg',
            sub5: 'https://i.ibb.co/9wXLrY7/sub-5.jpg',
            sub6: 'https://i.ibb.co/Zc3n6y0/sub-6.jpg',
            sub7: 'https://i.ibb.co/Js7kgPn/sub-7.jpg',
            sub8: 'https://i.ibb.co/GFnBkyR/sub-8.jpg',
            sub9: 'https://i.ibb.co/syHZPj8/sub-9.jpg',
          },
        },
        specifications: {
          dimensions: 'W 58 x L 24 x H 29 cm',
          weight: '13 kg',
          number: 30060,
        },
      },
      {
        id: 22,
        name: 'Braun T 520',
        path: 'braun-t-520-radio',
        price: 640,
        isSold: true,
        designer: ['dieter-rams'],
        description: `Beautiful design classic Braun T 520 radio designed in Germany by Dieter Rams (1962–1964). The iconic transistor is made of beige plastic and has an adjustable metal handle. The original antenna can be pulled out and is adjustable. The radio can be operated with 6 x 1.5V batteries (not included). The radio is in good condition and operational! Please note that this item is sold as decoration prestige collector's item and not intended for daily use due to its age.`,
        images: {
          main: 'https://i.ibb.co/mNzgPd5/main.png',
          thumbnail: 'https://i.ibb.co/XyykbQw/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/3hy1hSK/sub-1.jpg',
            sub2: 'https://i.ibb.co/S56hzrJ/sub-2.jpg',
            sub3: 'https://i.ibb.co/mzdSPdV/sub-3.jpg',
            sub4: 'https://i.ibb.co/pPCv4PZ/sub-4.jpg',
            sub5: 'https://i.ibb.co/nQ7BHLd/sub-5.jpg',
            sub6: 'https://i.ibb.co/BNm6NFL/sub-6.jpg',
          },
        },
        specifications: {
          dimensions: 'L 24,5 x W 6 x H 19,5 cm',
          weight: '1,4 kg',
          number: 30160,
        },
      },
    ],
  },
  {
    title: 'Clocks',
    order: 4,
    items: [
      {
        id: 23,
        name: 'Chronotechna clock',
        path: 'chronotechna-clock',
        price: 240,
        isSold: false,
        description: `Large vintage metal Chronotechna clock designed and made in Czechoslovakia in 1950s. The round clock is made of a metal body and used to be operated as by a central "mother clock". It has been converted to operate as an independent wall clock and comes with grey textile cable & german plug for 220V. Excellent condition: Partially renovated original.`,
        images: {
          main: 'https://i.ibb.co/DpgFcg7/main.png',
          thumbnail: 'https://i.ibb.co/LhSmq9B/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/yhnJFNq/sub-1.jpg',
            sub2: 'https://i.ibb.co/rt7Nm3J/sub-2.jpg',
            sub3: 'https://i.ibb.co/JHD5Mxb/sub-3.jpg',
            sub4: 'https://i.ibb.co/gV4JsyC/sub-4.jpg',
          },
        },
        specifications: {
          dimensions: 'L 7,5 x W 43,5 x H 43,5 cm',
          weight: '3 kg',
          number: 20011,
        },
      },
      {
        id: 24,
        name: 'Pragotron PK 27',
        path: 'pragotron-pk-27-wall-clock',
        price: 240,
        isSold: false,
        description: `Beautiful vintage industrial interior wall clock from Pragotron ( Model PK-27) in around plastic frame covered with glass. Designed & made in Czechoslovakia in 1960s. Converted to battery-powered clockwork, 1 x AA battery. Condition: Excellent condition.`,
        images: {
          main: 'https://i.ibb.co/nc2tQR8/main.png',
          thumbnail: 'https://i.ibb.co/KzR8qfg/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/Gn8R0Vc/sub-1.jpg',
            sub2: 'https://i.ibb.co/PzVtPg1/sub-2.jpg',
            sub3: 'https://i.ibb.co/rw9fnw4/sub-3.jpg',
          },
        },
        specifications: {
          dimensions: 'L 5 x W 34 x H 34 cm',
          weight: '1,5 kg',
          number: 30168,
        },
      },
      {
        id: 25,
        name: 'Braun BN0095',
        path: 'braun-bn0095-wrist-watch-quartz-black',
        price: 749,
        isSold: true,
        designer: ['dietrich-lubs'],
        description: `This Braun Prestige analogue watch measures 43mm diameter x D11 thick case. Available in stainless steel or black plated stainless steel. Both versions come with either stainless steel bracelet or rubber strap. The case of this Braun analogue watch is carved of one single block of steel. This one-piece’ construction eliminates the need for a case-back and in turn removes the element of potential leakage. The Swiss movement is mounted into the case from the top before being covered and sealed by the sapphire crystal. This allowed the Braun designers to taper the bottom part of the watch more elegantly and attach the band lugs in such a way that would not be possible with conventional watch construction. Implementing new technical solutions for the benefit of functionality has always been an important part of the Braun design tradition. The result is not only striking in appearance but moreover the elimination of a case back gives the watch an added structural advantage as there is a better protection against water. 2 year warranty. Watch case material: Stainless steel, Housing colour: Black, Band material: Rubber. Case diameter: 4.3 cm, Case thickness: 1.1 cm`,
        images: {
          main: 'https://i.ibb.co/RSSHPr7/main.png',
          thumbnail: 'https://i.ibb.co/JxGKLzg/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/0YdW6sw/sub-1.jpg',
            sub2: 'https://i.ibb.co/qBX2JDv/sub-2.jpg',
            sub3: 'https://i.ibb.co/CW7HQr4/sub-3.jpg',
            sub4: 'https://i.ibb.co/dQbbJBX/sub-4.jpg',
          },
        },
        specifications: {
          dimensions: 'W 2 x L 5 x H 25 cm',
          weight: '0,1 kg',
          number: 30148,
        },
      },
      {
        id: 26,
        name: 'Georg Jensen',
        path: 'georg-jensen-clock',
        price: 280,
        isSold: false,
        description: `Design classic wall clock "Georg Jensen" Copenhagen, Denmark by famous designer: Henning Koppel in 1978. Battery operated (not included). Great original condition with very minor patina.`,
        images: {
          main: 'https://i.ibb.co/6yfVD7V/main.png',
          thumbnail: 'https://i.ibb.co/K586Cdx/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/zb4bq7T/sub-1.jpg',
            sub2: 'https://i.ibb.co/tbBRScd/sub-2.jpg',
            sub3: 'https://i.ibb.co/j6gFG0r/sub-3.jpg',
          },
        },
        specifications: {
          dimensions: 'L 22 x W 22 x H 6 cm',
          weight: '1,4 kg',
          number: 30171,
        },
      },
      {
        id: 27,
        name: 'TN clock',
        path: 'tn-clock',
        price: 220,
        isSold: false,
        designer: ['dietrich-lubs'],
        description: `Large TN clock designed & made in Germany in the 1960s. The square clock is made of a transparent plastic body. Great outer condition: tiny scratches, working perfectly (new quartz mechanism (AA battery not included).`,
        images: {
          main: 'https://i.ibb.co/m0wd8ph/main.png',
          thumbnail: 'https://i.ibb.co/Svq5jqs/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/dm2fGNF/sub-1.jpg',
            sub2: 'https://i.ibb.co/6rvM9PH/sub-2.jpg',
            sub3: 'https://i.ibb.co/c8HcQt3/sub-3.jpg',
          },
        },
        specifications: {
          dimensions: 'L 7,5 x W 43,5 x H 43,5 cm',
          weight: '0,5 kg',
          number: 30169,
        },
      },
      {
        id: 28,
        name: 'Kienzle alarm clock',
        path: 'kienzle-alarm-clock',
        price: 80,
        isSold: false,
        designer: ['dietrich-lubs'],
        description: `The compact Kienzle alarm clock is equipped with an alarm signal and a quiet quartz mechanism. Its beautiful timeless design fits well into every designers hole. Like most of the world's very best timepieces, this clock operates in the analog domain, with a sweep second hand. Elegant red color plastic housing. Requires one AA battery (not included). Excellent original condition (working).`,
        images: {
          main: 'https://i.ibb.co/D9rhWn1/main.png',
          thumbnail: 'https://i.ibb.co/VjQs7pQ/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/JqBxkGK/sub-1.jpg',
            sub2: 'https://i.ibb.co/9VP3zbW/sub-2.jpg',
            sub3: 'https://i.ibb.co/dJGSY1G/sub-3.jpg',
          },
        },
        specifications: {
          dimensions: 'L 6,5 x W 3,5 x H 8 cm',
          weight: '0,1 kg',
          number: 30166,
        },
      },
      {
        id: 29,
        name: 'Braun Phase 2',
        path: 'braun-phase2',
        price: 80,
        isSold: true,
        designer: ['dietrich-lubs'],
        description: `Beautiful original BRAUN Phase II Type 4925 flip clock designed by Dietrich Lubs in the 1970s in beautiful black color. It is the new model that was released after the first edition Phase I. The condition is great, the housing has very few tiny scratches and little dust on the inner side. Functionality: Works fine, runs on 220V.`,
        images: {
          main: 'https://i.ibb.co/gRPHvjK/main.png',
          thumbnail: 'https://i.ibb.co/g4QYxht/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/XYfzW1B/sub-1.jpg',
            sub2: 'https://i.ibb.co/wddPykN/sub-2.jpg',
            sub3: 'https://i.ibb.co/pn63VJf/sub-3.jpg',
            sub4: 'https://i.ibb.co/zxBgYpC/sub-4.jpg',
            sub5: 'https://i.ibb.co/tsVJdtb/sub-5.jpg',
            sub6: 'https://i.ibb.co/9pfhvWM/sub-6.jpg',
          },
        },
        specifications: {
          dimensions: 'L 14 x W 8 x H 5 cm',
          weight: '0,35 kg',
          number: 30158,
        },
      },
      {
        id: 30,
        name: 'Braun BN0031 Ladies',
        path: 'braun-bn0031-wrist-watch-quartz-black',
        price: 135,
        isSold: false,
        description: `This Braun classic watch has an easy to read dial layout and features the iconic yellow second hand that is synonymous with Braun’s award winning design history. The clean simplistic dial and contrasting hands offers great legibility, and houses a precise quartz movement. Specifications: Case Diameter: 32mm / Case Depth: 7.95mm / Case Material: Stainless Steel /Dial Colour: White / Strap Width: 18mm / Strap Material: Leather Black / Clasp Type: Pin and Buckle / Movement: Quartz / Water Resistantance: 5ATM / Glass: Mineral Glass / Includes: Watch, presentation box, instruction manual & 2 year warranty`,
        images: {
          main: 'https://i.ibb.co/M5Gpsxn/main.png',
          thumbnail: 'https://i.ibb.co/GpwVfXD/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/HhqmDjr/sub-1.jpg',
            sub2: 'https://i.ibb.co/TvX0K46/sub-2.jpg',
            sub3: 'https://i.ibb.co/7zNYLBw/sub-3.jpg',
            sub4: 'https://i.ibb.co/2SdndTD/sub-4.jpg',
            sub5: 'https://i.ibb.co/NT8TGdq/sub-5.jpg',
          },
        },
        specifications: {
          dimensions: 'W 2 x L 5 x H 25 cm',
          weight: '0,1 kg',
          number: 30177,
        },
      },
      {
        id: 31,
        name: 'Braun BC02',
        path: 'braun-bc02-alarm-clock',
        price: 39,
        isSold: false,
        designer: ['dietrich-lubs'],
        color: ['Black', 'White', 'White/Black'],
        description: `The BC02XB classic travel analogue alarm clock features an easy to read dial layout and the iconic yellow second hand that has become synonymous with Braun’s award winning design history. The design of the BC02 originates from the renowned AB 1, designed in the late 80’s by Dietrich Lubs. Updated to include an improved movement and luminous tipped hour and minute hands. The clean simplistic dial and contrasting hands with luminous tips offer great legibility, and the quartz tick movement is quiet and precise. Its compact size (W5.7cm x H5.7cm x D2.7cm) and lightweight construction make it an ideal travel companion. Battery Type: AA *Not Included / Includes: Clock, instruction manual & 2 year warranty`,
        images: {
          main: 'https://i.ibb.co/KFwbJtz/main.png',
          thumbnail: 'https://i.ibb.co/zXQvHyP/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/LzTy8F1/sub-1.jpg',
            sub2: 'https://i.ibb.co/kKGPFr5/sub-2.jpg',
            sub3: 'https://i.ibb.co/6wSpcph/sub-3.jpg',
            sub4: 'https://i.ibb.co/ZT2JrJf/sub-4.jpg',
            sub5: 'https://i.ibb.co/56VszzN/sub-5.jpg',
            sub6: 'https://i.ibb.co/gSpVkjF/sub-6.jpg',
            sub7: 'https://i.ibb.co/Wgkrpkv/sub-7.jpg',
            sub8: 'https://i.ibb.co/Q9NP6jC/sub-8.jpg',
          },
        },
        specifications: {
          dimensions: 'W 5.7 x L 5.7 x H 2.7 cm',
          weight: '0,1 kg',
          number: 30179,
        },
      },
      {
        id: 32,
        name: 'Braun BN0031 Ladies',
        path: 'braun-bn0031-wrist-watch-quartz-gold',
        price: 190,
        isSold: false,
        color: ['Rose', 'Black/Rose', 'Silver'],
        description: `This timepiece is a classic interpretation of Braun core values of functionality, quality and aesthetics. A true embodiment of Braun’s award-winning clean approach to design. Specifications: Case Diameter: 32mm / Case Depth: 7.95mm Case Material: Stainless Steel / Colour: Rose Gold/White or Black/Gold Rose / Strap Width: 18mm / Strap Material: Stainless Steel or Leather / Clasp Type: Sliding Clasp / Movement: Quartz / Water Resistantance: 5ATM / Glass: Mineral Glass / Includes: Watch, presentation box, instruction manual & 2 year warranty`,
        images: {
          main: 'https://i.ibb.co/rw1P8sT/main.png',
          thumbnail: 'https://i.ibb.co/b5QxSmK/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/MDpFkJN/sub-1.jpg',
            sub2: 'https://i.ibb.co/9gZhv0t/sub-2.jpg',
            sub3: 'https://i.ibb.co/k9JZdQ6/sub-3.jpg',
            sub4: 'https://i.ibb.co/zfHVZqk/sub-4.jpg',
            sub5: 'https://i.ibb.co/4mrHVnd/sub-5.jpg',
            sub6: 'https://i.ibb.co/0fphrGF/sub-6.jpg',
            sub7: 'https://i.ibb.co/6rK39QR/sub-7.jpg',
            sub8: 'https://i.ibb.co/mXKGbsM/sub-8.jpg',
            sub9: 'https://i.ibb.co/mcZXQHn/sub-9.jpg',
            sub10: 'https://i.ibb.co/YpbTCdF/sub-10.jpg',
            sub11: 'https://i.ibb.co/0fF99VR/sub-11.jpg',
            sub12: 'https://i.ibb.co/H7Mfk45/sub-12.jpg',
          },
        },
        specifications: {
          dimensions: 'W 2 x L 5 x H 25 cm',
          weight: '0,1 kg',
          number: 30176,
        },
      },
      {
        id: 33,
        name: 'Philips HR 5401',
        path: 'philips-clock-hr-5401',
        price: 190,
        isSold: false,
        description: `Philips HR 5401 interior wall clock made of metal and plastic. Designed and made in Germany. Battery-powered clockwork, 1 x AA battery (not included). Condition: Patina scratches, good working condition.`,
        images: {
          main: 'https://i.ibb.co/BgRt0C0/main.png',
          thumbnail: 'https://i.ibb.co/wBS4s81/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/dkVhf2F/sub-1.jpg',
            sub2: 'https://i.ibb.co/2Zxdvhx/sub-2.jpg',
            sub3: 'https://i.ibb.co/NVWQF7P/sub-3.jpg',
          },
        },
        specifications: {
          dimensions: 'L 20 x W 25 x H 6 cm',
          weight: '1,6 kg',
          number: 30172,
        },
      },
    ],
  },
  {
    title: 'Home',
    order: 5,
    items: [
      {
        id: 34,
        name: 'Walter Gropius: Illustrated Biography',
        path: 'walter-gropius-biography-book',
        price: 125,
        isSold: false,
        description: `Pre-order now. This title will ship from September 8th, 2022. A stunning visual biography of the life of Walter Gropius, founder of the Bauhaus, and one of the world's most influential architects This illustrated biography tells the story of Gropius's life, beginning with his shattering experiences in World War One, his turbulent marriage to the notorious Alma Mahler, the establishment of the Bauhaus, and the tragic death of their daughter Manon. After Gropius's agonized decision to leave Nazi Germany in 1933, the book explores his life in exile in London and then his move to America in 1937, where he lived and worked until his death in 1969.Features more than 375 illustrations including letters, telegrams, sketches, drawings, photographs, posters, brochures, and other ephemera. The authors present the life of Walter Gropius as not just a key figure of 20th-century architecture, but as an extraordinarily generous person - a connector, protector, and benefactor who improved the lives and careers of all those with whom he came into contact. This is the first comprehensive illustrated biography of one of Modern architecture's most important figures. Specifications: Format: Hardback Size: 305 x 238 mm (12 x 9 3/8 in) Pages: 320 pp Illustrations: 377 illustrations ISBN: 9781838664213`,
        images: {
          main: 'https://i.ibb.co/MnfyHZ5/main.png',
          thumbnail: 'https://i.ibb.co/jbMW8Kr/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/JK1VX6G/sub-1.jpg',
            sub2: 'https://i.ibb.co/QCVkPs7/sub-2.jpg',
            sub3: 'https://i.ibb.co/BZwF2Bw/sub-3.jpg',
            sub4: 'https://i.ibb.co/4ZC73sz/sub-4.jpg',
            sub5: 'https://i.ibb.co/2WYpjnC/sub-5.jpg',
          },
        },
        specifications: {
          dimensions: 'W 30 x L 24 x H 6 cm',
          weight: '1,2 kg',
          number: 30139,
        },
      },
      {
        id: 35,
        name: 'Otl Aicher – Olympic Games Munich 1972',
        path: 'otl-aicher-olympic-games-munich-1972',
        price: 125,
        isSold: false,
        description: `Just under a quarter of a century after the end of National Socialism, Otl Aicher was commissioned to design the "cheerful" 1972 Munich Olympic Games. He went about his work systematically and scientifically, freeing visual communication from national pathos and reducing it to the essentials in the spirit of the Bauhaus: use. The manual, completed in 1967, is an astonishingly manageable set of rules, a flexible system of colors, shapes and type that allowed Aicher's team and partners to "play freely" and saved "unnecessary preliminary work and time-consuming detailed decisions." Aicher had a comprehensive claim: Everything should be able to be designed. With the results from over 100 design areas, he succeeded in creating an extraordinarily broad impact of the appearance and also set new standards in corporate design. To this day, Munich 1972 is considered the most successful design project of all the Olympic Games. ISBN 10: 3721209990 / ISBN 13: 9783721209990`,
        images: {
          main: 'https://i.ibb.co/q06fJcm/main.png',
          thumbnail: 'https://i.ibb.co/f87VGKz/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/G9Vx04x/sub-1.jpg',
            sub2: 'https://i.ibb.co/1fYjVhn/sub-2.jpg',
            sub3: 'https://i.ibb.co/yk06btv/sub-3.jpg',
            sub4: 'https://i.ibb.co/QjHyszw/sub-4.jpg',
            sub5: 'https://i.ibb.co/QFvFcK5/sub-5.jpg',
            sub6: 'https://i.ibb.co/KxhnBxG/sub-6.jpg',
          },
        },
        specifications: {
          dimensions: 'W 26 x L 2,8 x H 31,5 cm',
          weight: '1,8 kg',
          number: 30155,
        },
      },
      {
        id: 36,
        name: 'Dieter Rams: The Complete Works',
        path: 'dieter-rams-the-complete-works',
        price: 49,
        isSold: false,
        description: `Made in close collaboration with Rams himself, this catalogue raisonné is the ultimate reference on one of the most influential product designers of all time Dieter Rams is one of the most influential product designers of the twentieth century, who, for more than sixty years, has been defining the look, feel, and function of some of the world's best-loved consumer items. Using his 'ten principles for good design' as a philosophy and practice for improving the industry in a more holistic, responsible way, Rams has a stellar reputation with global resonance. This extraordinary book forms a catalogue raisonné of every product that Rams has designed in his lifetime – a true celebration of his seminal contribution to the field of industrial and product design. Including 300 color illustrations, the book is organized chronologically, each product is accompanied by a detailed description and specification breakdown, making this the ultimate reference guide for Rams fans and an ideal complement to Phaidon's global bestseller Dieter Rams: As Little Design as Possible. Delivery: Please note that the book is currently being reprinted and will be sent out early May 2023!!! Specifications: Format: Hardback Author: Klaus Klemp, with a foreword by Dieter Rams Publisher: Phaidon Size: 270 x 205 mm (10 5/8 x 8 1/8 in) Pages: 344 pp Illustrations: 300 illustrations ISBN: 9781838661533`,
        images: {
          main: 'https://i.ibb.co/PzVHvZp/main.png',
          thumbnail: 'https://i.ibb.co/Sy9GkQ8/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/zxzMtgv/sub-1.jpg',
            sub2: 'https://i.ibb.co/kh7Wh23/sub-2.jpg',
            sub3: 'https://i.ibb.co/1Mkvdkz/sub-3.jpg',
            sub4: 'https://i.ibb.co/kMvMnJ0/sub-4.jpg',
            sub5: 'https://i.ibb.co/QKLmc0Z/sub-5.jpg',
          },
        },
        specifications: {
          dimensions: 'W 27 x L 20 x H 5 cm',
          weight: '1,2 kg',
          number: 30130,
        },
      },
      {
        id: 37,
        name: 'Bauhaus 50 Years Exhibit Book',
        path: 'bauhaus-50-years-exhibit-book',
        price: 120,
        isSold: true,
        description: `Very rare Bauhaus 50 Years Exhibit book in great well-preserved condition- a reflection of on one of the greatest design schools including work by Walter Gropius, Marcel Breuer, Ludwig Mies Van Der Rohe, Laszlo Moholy-Nagy, Wassily Kandinsky, Josef Albers, Herbert Bayer and many others. / Text: original German edition / Color: In color and black and white / Pages: 365 / Design: Herbert Bayer / Year: 1970`,
        images: {
          main: 'https://i.ibb.co/2WWJ4HV/main.png',
          thumbnail: 'https://i.ibb.co/3vfJp3T/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/g3rQ3yX/sub-1.jpg',
            sub2: 'https://i.ibb.co/C6WHx1Z/sub-2.jpg',
            sub3: 'https://i.ibb.co/yBq6K2y/sub-3.jpg',
            sub4: 'https://i.ibb.co/kgVhmPS/sub-4.jpg',
            sub5: 'https://i.ibb.co/FmrKWVs/sub-5.jpg',
          },
        },
        specifications: {
          dimensions: 'W 22 x L 22 x H 2 cm',
          weight: '1,2 kg',
          number: 30130,
        },
      },
      {
        id: 38,
        name: 'The History of High-End Audio Design',
        path: 'the-history-of-high-end-audio-design',
        price: 75,
        isSold: false,
        description: `About the book: A beyond-cool look at the world of high-end audio design for passionate collectors, obsessive audiophiles, and design fans. At a time when sales of vinyl records have hit a 25-year high, and analog technologies are providing the kind of extraordinary audio experiences that our increasingly digital world has started to remove, Hi-Fi is essential reading. This unique book explores just how, when, and why the world fell in love with the look, feel, and sound of top-of-the-line audio equipment. Hi-Fi traces this fascinating evolution from the 1950s to today (and tomorrow), taking readers right up to the current renaissance of all things analog and the emergence of cutting-edge designs for die-hard audiophiles. Specifications: Publisher: Phaidon Format: Hardback Size: 270 x 205 mm (10 5/8 x 8 1/8 in) Pages: 272 pp Illustrations: 300 illustrations ISBN: 9780714878089`,
        images: {
          main: 'https://i.ibb.co/nrybrx7/main.png',
          thumbnail: 'https://i.ibb.co/BfNy2mM/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/cJrBCr7/sub-1.jpg',
            sub2: 'https://i.ibb.co/8Ykc69R/sub-2.jpg',
            sub3: 'https://i.ibb.co/mTjWk4R/sub-3.jpg',
            sub4: 'https://i.ibb.co/w6gKw5k/sub-4.jpg',
            sub5: 'https://i.ibb.co/5vZjmf6/sub-5.jpg',
            sub6: 'https://i.ibb.co/FYGdfVF/sub-6.jpg',
            sub7: 'https://i.ibb.co/n7Ktfj0/sub-7.jpg',
            sub8: 'https://i.ibb.co/GVh2NSk/sub-8.jpg',
            sub9: 'https://i.ibb.co/2yP3DtN/sub-9.jpg',
          },
        },
        specifications: {
          dimensions: 'W 27 x L 20 x H 5 cm',
          weight: '1,2 kg',
          number: 30130,
        },
      },
      {
        id: 39,
        name: 'Braun TFG 2',
        path: 'braun-tfg-2-cylindric-table-lighter',
        price: 230,
        isSold: false,
        designer: ['dieter-rams'],
        description: `Braun Cylindric TFG 2 table lighter designed by Dieter Rams between 1968 and 1970 in Germany. Being one of the most iconic table lighters, this model consists of a silver brushed chrome steel top and thermoplastic body. The lighter is in very good preserved outer condition. Please note that it will be shipped empty without gas (transportation requirements).`,
        images: {
          main: 'https://i.ibb.co/F07b2py/main.png',
          thumbnail: 'https://i.ibb.co/SNVgPGN/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/418529c/sub-1.jpg',
            sub2: 'https://i.ibb.co/SN2Ym3r/sub-2.jpg',
          },
        },
        specifications: {
          dimensions: 'L 5,5 x W 5,5 x H 8,8 cm',
          weight: '0,2 kg',
          number: 30015,
        },
      },
      {
        id: 40,
        name: 'German typography board',
        path: 'german-typography-board',
        price: 210,
        isSold: false,
        description: `Beautiful vintage German school education poster board with broken type explanations including words and letters. Each cardboard is printed on both sides. Only sold as a set. Stunning capital lettering and typography – a true piece of art and design. Published R.Oldenbourg Verlag München by Röhr-Verlag München. Estimated time of print: 1910 - 1930. Printed on cardboard with beautiful patina (partly demaged paper) Very good condition due to stunning age.`,
        images: {
          main: 'https://i.ibb.co/QHPRtcJ/main.png',
          thumbnail: 'https://i.ibb.co/85wfSy1/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/k3HPn2v/sub-1.jpg',
            sub2: 'https://i.ibb.co/bzkSwXC/sub-2.jpg',
            sub3: 'https://i.ibb.co/FK80Lng/sub-3.jpg',
            sub4: 'https://i.ibb.co/Wn7xDB4/sub-4.jpg',
            sub5: 'https://i.ibb.co/2FmjwBB/sub-5.jpg',
            sub6: 'https://i.ibb.co/QdKdQ30/sub-6.jpg',
            sub7: 'https://i.ibb.co/QnNsQ5n/sub-7.jpg',
            sub8: 'https://i.ibb.co/pbm99W0/sub-8.jpg',
          },
        },
        specifications: {
          dimensions: 'W 62 x H 85 cm',
          weight: '1,3 kg',
          number: 40013,
        },
      },
      {
        id: 41,
        name: 'Lundtofte Menage set',
        path: 'lundtofte-menage-set',
        price: 120,
        isSold: true,
        description: `Beautiful Lundtofte Denmark Menage Set made of Teak wood and Stainless steel in, consisting of Salt, Pepper shakers, a Sugar pot and a tray. Classic timeless Danish design - simple & elegant made in the 1960s. We believe that the designer behind it is no other than the famous Danish designer Georg Jensen. The tray has indentations for each of the the pots. Both the shaker and the central pot are in a great preserved condition and can be used daily.`,
        images: {
          main: 'https://i.ibb.co/MfDxB4g/main.png',
          thumbnail: 'https://i.ibb.co/Ms41Yfd/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/k1XskTX/sub-1.jpg',
            sub2: 'https://i.ibb.co/LhVKnf7/sub-2.jpg',
            sub3: 'https://i.ibb.co/BTvRJSc/sub-3.jpg',
            sub4: 'https://i.ibb.co/0t8mLry/sub-4.jpg',
            sub5: 'https://i.ibb.co/Y035Xth/sub-5.jpg',
          },
        },
        specifications: {
          dimensions: 'W 18 x L 6 x H 8 cm',
          weight: '0,2 kg',
          number: 30108,
        },
      },
      {
        id: 42,
        name: 'Braun Photography Prints',
        path: 'braun-photography-prints',
        price: 45,
        isSold: true,
        description: `Various Braun Art black & white photography taken in 1960s-70s for an art BRAUN calendar. The photography has been reproduced and printed on thicker white paper. Ideal for decoration purposes (to be framed). The art prints feature the Braun T22 radio, Phonosuper SK 4 or the PK G 5 just to name a few. Please place the order and notify us which art print you selected (A - G). Price per piece!`,
        images: {
          main: 'https://i.ibb.co/Qjq2PP5/main.png',
          thumbnail: 'https://i.ibb.co/HCj3bMr/thumbnail.jpg',
          sub: {
            sub1: 'https://i.ibb.co/2KMdPHd/sub-1.jpg',
            sub2: 'https://i.ibb.co/60XyWgG/sub-2.jpg',
            sub3: 'https://i.ibb.co/HC0TMcf/sub-3.jpg',
            sub4: 'https://i.ibb.co/KLQBmvP/sub-4.jpg',
          },
        },
        specifications: {
          dimensions: 'W 42,0 x L 30,0 cm',
          weight: '0,1 kg',
          number: 30126,
        },
      },
    ],
  },
]

export default PRODUCTS_DATA
